dist: bionic

jobs:
  include:
  - name: Enterprise 1.3.0.x
    env: KONG_VERSION=1.3.0.x
  - name: Enterprise 1.5.0.x
    env: KONG_VERSION=1.5.0.x
  - name: Kong CE 1.3.x
    env: KONG_VERSION=1.3.x
  - name: Kong CE 1.5.x
    env: KONG_VERSION=1.5.x
  - name: Kong CE 2.0.x
    env: KONG_VERSION=2.0.x

before_install:
- sudo apt-get -y install make

install:
- make install_pongo

script:
- make pongo

package:
- make package